//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSusingCsharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string empcode { get; set; }
        public string empname { get; set; }
        public string address { get; set; }
        public string phoneno { get; set; }
        public string designation { get; set; }
        public string salary { get; set; }
        public System.DateTime joindate { get; set; }
        public byte[] img { get; set; }
    }
}
